### PR TITLE
Improve Debug-Experience and Readability

### PR DESCRIPTION
**Pull request by manuth**
This PR provides the functionality to basically debug the project, especially using Visual Studio Code, and improves the readability of libips.cpp.

I've done this while having a look at your code in order to learn more about your algorithm and for using it in my own project.

Thanks again for your great help - that's awesome, dude 😄

### CODE REVIEW

**Comment by manuth** [comment]
> Looks like this is one of your first PRs? Many open source maintainers prefer one PR per change

You're totally right - this, honestly, is the first time I'm collborating using git in any way - 'til now I've been coding solo :')  
I'll remember that and next time I won't provide that many changes in one PR.

```diff
+ // Verwendet IntelliSense zum Ermitteln möglicher Attribute.
```

I really haven't noticed the auto-generated files contain German comments this can be fixed in just a second.

> The unoptimized build is better created with 'make' or 'make CFLAGS=-g', I'd rather not break that.

Currently I'm adding either `-O0 -g` or `-O3` according to the $MODE-variable.  
Is there some smoother way to do that?

> Also nobody except Microsoft calls binaries 'assembly'.

You sure have noticed I'm a clicky-bounty-Microsoft user - changes made to the `make.sh` are based on MSBuild-defaults - that's why the namings look similar.

Of course these superfluous variables can be replaced.

> The intention is that the read8s should line up. Mine does if tab width is 2, yours requires 4. Should be spaces, they work for everyone.

Looks like I messed up my editor settings - usually I have my identation set to 4 spaces instead of tab.

> Good idea, but if the source file is above 16MB and the target is exactly 16MB, I suspect it'll emit an instruction to truncate to 0 bytes. Better add if (targetlen>=16777216 && sourcelen>targetlen) return ips_16MB; // can't truncate to 16MB as well.

Understood! It's because in that case the length of the target is added to the end of the patch, right?  
In that case, I think, `if (sourcelen != targetlen && targetlen >= 0xFFFFFF)` would match perfect...?

> I'm not sure if you ran an autoformatter

Point for you! Yeah - honestly I first ran an autoformatter over `libips.cpp` and then added some line breaks and curly braces by myself since gdb seems to just skip expressions that are kept on a single line such as

```cpp
		while (offset<sourcelen && (offset<sourcelen?source[offset]:0)==target[offset]) offset++;
```

> Do you want me to implement most of those comments (everything except VSCode... )

I honestly don't know what comments you mean, I'm sorry 😅 

> and while I can guess how to make it use makefile, I can't test it

Well it's actually pretty easy since I've created all configuration-files that are required.  
You just need to install the [C/C++-Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools) available on the Marketplace and press <kbd>CTRL</kbd>+<kbd>B</kbd> in order to build the project or <kbd>F5</kbd> in order to build the project with `-g` and `-O0`-flags set and launch the debugger.

> Nontrivial PRs often get a few rounds of comments before they're merged, it's nothing unusual.

Don't you worry, I won't get you wrong. It's real cool you're having a look at the changes I've made and you consider implementing them ^^

**Comment by Alcaro** [comment]
> Is there some smoother way to do that?

As I said, better leave make.sh alone for debug builds, it's highly tuned for optimization. All the -f in FLAGS are various optimizations; compiling twice with profile.sh in between is profiling, which is an optimization. Better call 'make' or 'make CFLAGS=-g' directly from VSCode for debug.

> Looks like I messed up my editor settings - usually I have my identation set to 4 spaces instead of tab.

I prefer tab for indentation and space for alignment. Not sure how many IDEs support that.

> It's because in that case the length of the target is added to the end of the patch, right?

Yes, IPSes end with the target size if the source is bigger. But we still need the 'target >= 0x01000001' check, IPS can't write beyond 16MB even if the target is bigger.

While it's theoretically possible to emit a 64K-1 block of mostly unchanged data starting at 16M-1, allowing the target to be 16M+64K-2 bytes, Flips doesn't support creating such patches, it prefers you switch to BPS. And even if it was supported, 16M+64K-2 bytes is still a limit that should be checked for. (Feel free to implement that in your patcher and claim you have a feature I don't.)

Not sure if Flips supports applying such a patch, either. It should, but it's untested and may be buggy.

> since gdb seems to just skip expressions that are kept on a single line

Ah, so that's what you're doing. Yeah, then linebreaks make sense. Personally I do much of my debugging by spamming print statements all over, but making things easy for gdb is a valid concern. I'll try to limit oneliner if statements in my other projects.

> I honestly don't know what comments you mean, I'm sorry 😅

My complaints in my prior comment. Someone has to fix them, your choice which of us.

> Well it's actually pretty easy since I've created all configuration-files that are required.

That'd work if I had VSCode installed, but I don't, and I hate installing stuff if I'm not going to use it a lot. I'll just trust that you've tested them properly.

**Comment by manuth** [comment]
I just fixed the indentation and the code-design itself - I think it should be right the way you want it to be like.

> Better call 'make' or 'make CFLAGS=-g' directly from VSCode for debug.

Okay - I've done that now in b44b4f0 and 7e0b310.

> Yes, IPSes end with the target size if the source is bigger. But we still need the 'target >= 0x01000001' check, IPS can't write beyond 16MB even if the target is bigger.
>
>While it's theoretically possible to emit a 64K-1 block of mostly unchanged data starting at 16M-1, allowing the target to be 16M+64K-2 bytes, Flips doesn't support creating such patches, it prefers you switch to BPS.

I just tried to adjust the size-restriction until I realized it'd cause bugs if a part after `0x1000000` 'd look the same.  
I think the current size-restriction I wrote in 1fc8570 should work out perfectly.

>  Personally I do much of my debugging by spamming print statements all over

To be honest this is the very first C/CPP-project I'm working on - I wouldn't even know how to print stuff to the debug-console 😂

> My complaints in my prior comment. Someone has to fix them, your choice which of us.

Alright - I just fixed this in 63781b4. The auto-generated comments are now in English.

>

**Comment by Alcaro** [comment]
This PR is starting to get fairly messy.

> Okay - I've done that now in b44b4f0 and 7e0b310.

Looks good to me. I'm not completely sure if that one passes the variables you made the makefile expect, but that's better fixed in the makefile. Let's not make VSCode the only way to build Flips. (I think VSCode can call Makefiles without going via the shell, but that doesn't make any real difference.)

> I think the current size-restriction I wrote in 1fc8570 should work out perfectly.

Yeah, that looks good.

> To be honest this is the very first C/CPP-project I'm working on - I wouldn't even know how to print stuff to the debug-console joy

Print spam debugging, also known as printf debugging, is a common technique in almost all languages. It works just as well in C# as C++.

These parts of the PR are definitely improvements:
- Allow target size 0x01000000
- More linebreaks, rather than oneliners
- More spacing around operators and comments
- More VSCode support
- Putting profiling data and Windows resource object files in a subdirectory
- Splitting the 'rle-worthy before another rle-worthy' condition to multiple lines
- Making make.sh less me-specific by removing mv flips ~/bin/flips

These improve some things, but worsen others, and as far as I can see, the sum is negative; unless you feel I'm wrong (perhaps I am), they should be reverted:
- Making output locations configurable
- Making the Makefile demand BINPATH, PROJECT and a few other variables to exist
- Removing that linebreak near the Flips/LIPS comparison
- Attaching asterisks to the variable names
- -rf on the rm seems unneeded; unless they're known useful, they should be removed, especially if there's variables nearby; [bugs there tend to be dangerous](https://github.com/valvesoftware/steam-for-linux/issues/3671)

These could be improved, but are suboptimal in the current version too, I won't expect you to fix them (but you may if you want to):
- Tab/space confusion on read8s
- Clarify the relation between make.sh and Makefile
- Size-0 RLE should return ips_invalid, rather than poke w_scrambled (other uses of w_scrambled should remain)
- Too many linebreaks above 'check if RLE here is worthwhile'; two lines per condition is enough, five is excessive

Once the middle list is empty, I'll merge this and fix whatever remains in the third list.

**Comment by manuth** [comment]
Aite - I think I patched everything...?  
The makefile is independent now and doesn't depend on variables such as PROJECT or BINPATH.  
Everything else is patched, too

**Comment by Alcaro** [comment]
oh right, I forgot this one.

All those reversions/etc make it hard to merge, so I copypasted the good parts. Did I miss anything?

**Comment by Alcaro** [comment]
No answer, I'll just assume everything is fine.

**Pull request closed without merging**
