### PR TITLE
Use GTKFileChooserNative instead of GTKFileChooser

### LINKED ISSUE #69: Use GTKFileChooserNative instead of GTKFileChooser
The native variants make the GTK build nicer on Linux platforms, due to it using the filepicker/save of the system environment, rather than always using GTK.
I think this just involves changing the `gtk_file_chooser_dialog_new`  calls with `gtk_file_chooser_native_new`. Will probably try to do a PR for this.
May or may not need to change the #define GDK_VERSION_MIN_REQUIRED at the top of the file, not sure.

### PR DESCRIPTION
**Pull request by Miepee**
Fixes #69

I have tested this by using the `Apply Patch` and `Create Patch` functions. They didn't have any regressions.
`Apply and Run` also didn't have any functional regressions. But the custom executable filter was removed due to it not being supported on native file pickers (see comment).

### CODE REVIEW

**Comment by Miepee** [comment]
is CI just broken? Its error message doesnt seem to line up with my diff.

**Comment by Alcaro** [comment]
Looks like the CI was trying to use Ubuntu 18.04, which is no longer supported and apparently no longer functional.

I switched it to 22.04. Rebase your pull, and it should work better.

(The Windows CI has a pretty old mingw, too... but Flips doesn't use any advanced features, so it's fine. For now.)

**Comment by Miepee** [comment]
ty, seems to have worked!

**Comment by Alcaro** [comment]
Looks good to me, and if it also looks good to you and the CI, let's just trust it is good.

**Pull request merged**
